### ISSUE TITLE
Problem with "reachability distance" formula

### ISSUE THREAD

**Issue by nguyenhuuthuat09** [czhongyu/outlier-detection#1]
Hi, i have read your code and i have to say that it is a beautiful code. but it seems to have a small problem at below line in lof.py file.

https://github.com/czhongyu/outlier-detection/blob/842e14d7c011951728888ec249b4077be3f8f8ec/lof.py#L48

I think it should be: `rd += max(dis[index][i], dis[kdn[index][i]][-1]) `  (max instead of min)

I read some articals about this algorithm, and and they all seem to use max instead of min. For example in this artical: https://en.wikipedia.org/wiki/Local_outlier_factor

And i try to compare your result from your code with sklearn.neighbors.LocalOutlierFactor, when i change min to max, they give the same result.

And by the way, thank you for your great code.

**Comment by zhongyuchen** [comment]
@nguyenhuuthuat09 
Thank you for your comments! That's very nice of you and it means a lot to me! ❤️  As to your suggestion on using `max` instead of `min`, I couldn't agree more and I'll get to it right away!
